name: Git Checker

on: [push, pull_request]

jobs:
  git-checker:
    runs-on: ubuntu-latest
    env:
      repo: `cat address.txt`
      path: git-majonez
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Checkout git-majonez repo
      uses: actions/checkout@v2
      with:
        repository: env.repo
        path: env.path
    - name: Run tree-check.sh
      working-directory: .github/scripts
      run: ./tree-check.sh ../../env.path
    - name: Run history-check.sh
      working-directory: .github/scripts
      run: ./history-check.sh ../../env.path/history.txt
